### ISSUE TITLE
MAC addresses like FF:00:FF:FF:FF can not be used

### ISSUE THREAD

**Issue by publicarray** [mlichvar/ntpperf#1]
MAC addresses like `FF:00:FF:FF:FF` can not be used due to this check `!config.dst_mac[1]` 
https://github.com/mlichvar/ntpperf/blob/cc34f1f1628745c4a4cf92aceae310231bc04807/perf.c#L605

**Comment by mlichvar** [comment]
Should be fixed now. Thanks for the report.

**Comment by publicarray** [comment]
Ah thank you!
