### ISSUE TITLE
Compilation fails with NTPPERF_NTS enabled 

### ISSUE THREAD

**Issue by saurabh082** [mlichvar/ntpperf#3]
I am trying to compile the code using NTPPERF_NTS enabled, also installed gnutls using below commands -

- yum install -y gnutls-devel
- yum list installed gnutls
Installed Packages
gnutls.x86_64                                                                                                     3.3.29-9.amzn2                                                                                                      @amzn2-core

but it fails with following errors, could you please help on this?

[ec2-user@ip-xxx-xx-xx-xxx]$ make NTPPERF_NTS=1
cc -O2 -Wall -g -I/usr/include/p11-kit-1   -D_GNU_SOURCE -DNTS  -c -o sender.o sender.c
In file included from sender.c:31:0:
/usr/include/gnutls/crypto.h:35:10: error: unknown type name ‘gnutls_cipher_algorithm_t’
          gnutls_cipher_algorithm_t cipher,
          ^
/usr/include/gnutls/crypto.h:36:10: error: unknown type name ‘gnutls_datum_t’
          const gnutls_datum_t * key,
          ^
/usr/include/gnutls/crypto.h:37:10: error: unknown type name ‘gnutls_datum_t’
          const gnutls_datum_t * iv);
          ^
/usr/include/gnutls/crypto.h:59:34: error: unknown type name ‘gnutls_cipher_algorithm_t’
 int gnutls_cipher_get_block_size(gnutls_cipher_algorithm_t algorithm);
                                  ^
/usr/include/gnutls/crypto.h:60:31: error: unknown type name ‘gnutls_cipher_algorithm_t’
 int gnutls_cipher_get_iv_size(gnutls_cipher_algorithm_t algorithm);
                               ^
/usr/include/gnutls/crypto.h:61:32: error: unknown type name ‘gnutls_cipher_algorithm_t’
 int gnutls_cipher_get_tag_size(gnutls_cipher_algorithm_t algorithm);
                                ^
/usr/include/gnutls/crypto.h:66:34: error: unknown type name ‘gnutls_mac_algorithm_t’
 size_t gnutls_mac_get_nonce_size(gnutls_mac_algorithm_t algorithm);
                                  ^
/usr/include/gnutls/crypto.h:68:8: error: unknown type name ‘gnutls_mac_algorithm_t’
        gnutls_mac_algorithm_t algorithm,
        ^
/usr/include/gnutls/crypto.h:75:25: error: unknown type name ‘gnutls_mac_algorithm_t’
 int gnutls_hmac_get_len(gnutls_mac_algorithm_t algorithm);
                         ^
/usr/include/gnutls/crypto.h:76:22: error: unknown type name ‘gnutls_mac_algorithm_t’
 int gnutls_hmac_fast(gnutls_mac_algorithm_t algorithm,
                      ^
/usr/include/gnutls/crypto.h:81:8: error: unknown type name ‘gnutls_digest_algorithm_t’
        gnutls_digest_algorithm_t algorithm);
        ^
/usr/include/gnutls/crypto.h:85:25: error: unknown type name ‘gnutls_digest_algorithm_t’
 int gnutls_hash_get_len(gnutls_digest_algorithm_t algorithm);
                         ^
/usr/include/gnutls/crypto.h:86:22: error: unknown type name ‘gnutls_digest_algorithm_t’
 int gnutls_hash_fast(gnutls_digest_algorithm_t algorithm,
                      ^
sender.c:48:2: error: unknown type name ‘gnutls_aead_cipher_hd_t’
  gnutls_aead_cipher_hd_t cipher;
  ^
sender.c: In function ‘initialize_nts’:
sender.c:76:2: error: unknown type name ‘gnutls_datum_t’
  gnutls_datum_t datum;
  ^
sender.c:81:15: warning: assignment makes integer from pointer without a cast [enabled by default]
   nts->cipher = NULL;
               ^
sender.c:92:7: error: request for member ‘data’ in something not a structure or union
  datum.data = key;
       ^
sender.c:93:7: error: request for member ‘size’ in something not a structure or union
  datum.size = convert_hex_to_bytes(config->nts.c2s, key, sizeof key);
       ^
sender.c:95:2: warning: implicit declaration of function ‘gnutls_aead_cipher_init’ [-Wimplicit-function-declaration]
  if (gnutls_aead_cipher_init(&nts->cipher, GNUTLS_CIPHER_AES_128_SIV, &datum) < 0) {
  ^
sender.c:95:44: error: ‘GNUTLS_CIPHER_AES_128_SIV’ undeclared (first use in this function)
  if (gnutls_aead_cipher_init(&nts->cipher, GNUTLS_CIPHER_AES_128_SIV, &datum) < 0) {
                                            ^
sender.c:95:44: note: each undeclared identifier is reported only once for each function it appears in
sender.c:96:52: error: request for member ‘size’ in something not a structure or union
   fprintf(stderr, "Invalid key length: %d\n", datum.size);
                                                    ^
sender.c: In function ‘destroy_nts’:
sender.c:109:3: warning: implicit declaration of function ‘gnutls_aead_cipher_deinit’ [-Wimplicit-function-declaration]
   gnutls_aead_cipher_deinit(nts->cipher);
   ^
sender.c: In function ‘make_packet’:
sender.c:220:3: warning: implicit declaration of function ‘gnutls_aead_cipher_encrypt’ [-Wimplicit-function-declaration]
   if (gnutls_aead_cipher_encrypt(nts->cipher,
   ^
make: *** [sender.o] Error 1

**Comment by mlichvar** [comment]
That gnutls version is too old for the NTS support. I think you need at least 3.6.14 (e.g. available in RHEL8-based systems).

**Comment by saurabh082** [comment]
Thanks. I tried with RHEL8 and gnutls version 3.6.14 and able to compile it successfully with NTPPERF_NTS enabled.
