### ISSUE TITLE
Does ndtperf support PTP perf testing in multicast-mode?

### ISSUE THREAD

**Issue by Gunterwa** [mlichvar/ntpperf#5]

**Comment by mlichvar** [comment]
There is now -M option implemented to enable PTP multicast. You will still need to specify the address of the server. There is no multicast join, so this will work only in a local segment where the responses from the server can be seen.

**Comment by Gunterwa** [comment]
Got it, appreciate!




On 06/28/2022 19:49，Miroslav ***@***.***> wrote：

There is now -M option implemented to enable PTP multicast. You will still need to specify the address of the server. There is no multicast join, so this will work only in a local segment where the responses from the server can be seen.
